default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :tests do
    run_tests(
      devices: ["iPhone 16 Pro"],
      scheme: "GitHubAPI",
      skip_testing: ["GitHubAPIUITests"]
    )
  end

  desc "Build app"
  lane :build do
    gym(
      scheme: "GitHubAPI"
    )
  end

end
